### ISSUE TITLE
RestoreTransactions returns empty array

### ISSUE THREAD

**Issue by smikheiev** [freshplanet/ANE-In-App-Purchase#32]
RestoreTransaction method returns empty array. Doesn't it work or maybe i use it in wrong way?
The problem is on iOS.

**Comment by elmortem** [comment]
I have this problem too.

**Comment by ZwickTheGreat** [comment]
Did you call init() before calling restoreTransactions()?

**Comment by roguenet** [comment]
The problem is that the iOS implementation (in Actionscript) of restoreTransactions completely misses the point of what restoreTransactions() is supposed to do. It just "restores" transactions that are currently sitting in memory in the pending queue of the current app. Restore transactions is supposed to let a person that deleted the app retrieve the items they'd previously purchased. 

I ended up implementing this myself, but unfortunately have not yet had time to clean it up into a PR to this repo. You can see the iOS side in the last couple of commits in my fork: https://github.com/roguenet/ANE-In-App-Purchase/commits/develop. Unfortunately, the AS side is in a private repo, as I have my own AS implementation.

The AS is pretty straightforward though. You need simply to call _extCtx.call("restoreTransactions"); After that, the onStatus() method in AS will receive TRANSACTION_RESTORED and TRANSACTION_RESTORE_FINISHED with potential TRANSACTION_RESTORE_FAILED in there. 

It was a couple of months ago that I did all that, but I think that was all there is to it. Hopefully I get a chance to put together a PR soon so people don't have to jump hoops to get access to this feature. It's so basic to the requirements of an app that has non-consumable purchases, and the implementation is straightforward, so I have no idea why Freshplanet didn't include it to begin with.

**Comment by esdebon** [comment]
I fixed the problem adding a parameter to the restoreTransactions method.

With this you retrieve the items from the appstore:
InAppPurchase.getInstance().restoreTransactions(true);

https://github.com/Fluocode/ANE-In-App-Purchase

**Comment by iBros** [comment]
@esdebon Can you commit this to the original branch? This issue is still there (it's OK in your code) and your fork misses other fixes that were made.

**Comment by yvant** [comment]
Hi, I personnaly still have an empty array as a return... level="{"details":{},"purchases":[]} Is it because I test it on a dev mode? getProductsInfo works and returns me the right description of the inApp purchase. Did I miss anything?
